simplr_install:
    resource: "@CleentfaarSimplrCmsBundle/Resources/config/routing_install.yml"
    prefix:   /_install

simplr_backend:
    resource: "@CleentfaarSimplrCmsBundle/Resources/config/routing_backend.yml"
    prefix:   /admin

simplr_frontend:
    resource: "@CleentfaarSimplrCmsBundle/Resources/config/routing_frontend.yml"
    prefix:   /

