simplr_install_welcome:
    pattern:  /
    defaults: { _controller: Cleentfaar\Simplr\Core\Controller\Install\WelcomeController::indexAction }

simplr_install_check:
    pattern:  /check
    defaults: { _controller: Cleentfaar\Simplr\Core\Controller\Install\CheckController::indexAction }

simplr_install_update:
    pattern:  /update
    defaults: { _controller: Cleentfaar\Simplr\Core\Controller\Install\UpdateController::indexAction }

simplr_install_about:
    pattern:  /about
    defaults: { _controller: Cleentfaar\Simplr\Core\Controller\Install\AboutController::indexAction }

simplr_install_wizard:
    pattern:  /wizard
    defaults: { _controller: Cleentfaar\Simplr\Core\Controller\Install\WizardController::indexAction }